"""Pydantic contracts between the feature layer, LLM layer, and execution layer.

These are the *interfaces* — not DB models.  They define what data flows
between phases and are versioned here so each phase can evolve independently.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

# ── Enumerations ───────────────────────────────────────────────────────────────


class Regime(StrEnum):
    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    RANGING = "ranging"
    HIGH_VOLATILITY = "high_volatility"
    UNKNOWN = "unknown"


class TradeLean(StrEnum):
    LONG = "long"
    SHORT = "short"
    NO_TRADE = "no_trade"


class TradeDirection(StrEnum):
    LONG = "long"
    SHORT = "short"


# ── Feature snapshot (in-memory, before DB persistence) ───────────────────────


class FeatureVector(BaseModel):
    """All computed features at a single decision point."""

    symbol: str
    ts: datetime

    # Price context
    close: float
    open: float | None = None
    high: float | None = None
    low: float | None = None
    volume: float | None = None

    # Moving averages (daily candles)
    sma_20d: float | None = None
    sma_50d: float | None = None
    sma_200d: float | None = None

    # Intraday
    vwap: float | None = None
    above_vwap: bool | None = None

    # Volatility
    atr_14d: float | None = None
    atr_pct: float | None = None  # atr / close * 100

    # Volume
    rvol: float | None = None  # relative volume vs 20-day avg same bar

    # Trend
    trend_1d: str | None = None  # "up" | "down" | "flat"

    # Gap
    gap_pct: float | None = None

    # VIX (may be None on free tier)
    vix: float | None = None

    # Extras for forward compat
    extra: dict[str, Any] = Field(default_factory=dict)


# ── Regime assessment (LLM output) ───────────────────────────────────────────


class RegimeAssessment(BaseModel):
    """Structured output from the LLM Research Director.

    This is the *contract*: the LLM must return JSON conforming to this schema.
    Strict validation is enforced — malformed output triggers a retry.
    """

    regime: Regime
    lean: TradeLean
    confidence: int = Field(ge=1, le=10, description="Conviction 1–10")
    reasoning: str = Field(description="One-paragraph human-readable rationale")
    key_risks: list[str] = Field(description="Top 2–4 risk factors")
    invalidation: str = Field(description="What would invalidate this assessment")

    # Cost / audit metadata (populated by LLM adapter, not by the model itself)
    prompt_version: str = "v1"
    model_used: str = ""
    input_tokens: int = 0
    output_tokens: int = 0
    latency_ms: int = 0


# ── Trade thesis (strategy output) ────────────────────────────────────────────


class TradeThesis(BaseModel):
    """A proposed trade generated by a strategy after passing the LLM gate.

    The risk filter and execution layer consume this.
    """

    symbol: str
    direction: TradeDirection
    entry_price: float
    stop_loss: float
    take_profit: float

    # Risk metrics
    risk_per_share: float | None = None  # entry - stop
    reward_per_share: float | None = None  # take_profit - entry
    risk_reward: float | None = None  # reward / risk

    # Context that produced the thesis
    regime_assessment: RegimeAssessment | None = None
    features: FeatureVector | None = None

    # Strategy metadata
    strategy_name: str = ""
    strategy_version: str = "v1"
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    # Human-readable
    rationale: str = ""

    def model_post_init(self, __context: Any) -> None:
        if self.entry_price and self.stop_loss and self.take_profit:
            risk = abs(self.entry_price - self.stop_loss)
            reward = abs(self.take_profit - self.entry_price)
            self.risk_per_share = risk
            self.reward_per_share = reward
            self.risk_reward = reward / risk if risk > 0 else None
