/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as StrategyRouteImport } from './routes/strategy';
import { Route as PaperRouteImport } from './routes/paper';
import { Route as NewsRouteImport } from './routes/news';
import { Route as IndexRouteImport } from './routes/index';
const StrategyRoute = StrategyRouteImport.update({
    id: '/strategy',
    path: '/strategy',
    getParentRoute: () => rootRouteImport,
});
const PaperRoute = PaperRouteImport.update({
    id: '/paper',
    path: '/paper',
    getParentRoute: () => rootRouteImport,
});
const NewsRoute = NewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    NewsRoute: NewsRoute,
    PaperRoute: PaperRoute,
    StrategyRoute: StrategyRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
